### ISSUE TITLE
misdefined and used variables exists which cause script failure. expl. below.

### ISSUE THREAD

**Issue by Kuduzkehpan** [HAMM3REXTREME/ComfyUI-Installer#1]
in install.sh at line 8 variable defined   "comfyui_repo" 
but at line 19 git clone $comfyui_main_repo variable tried to be used. which is blank and gives error at line 20 cuz there is no git clone cloned. as comfyui name.

**Comment by HAMM3REXTREME** [comment]
Oops. Should be fixed now.
