### ISSUE TITLE
Launch error

### ISSUE THREAD

**Issue by nijahplays** [HAMM3REXTREME/ComfyUI-Installer#2]
ComfyUI-Installer/launch.sh: line 4: sdg/bin/activate: No such file or directory

Not sure why it's doing this

**Comment by nijahplays** [comment]
Fixed temporarily by changing the comfyui launch script in /ComfyUI to `source comfy-venv/bin/activate` and running through all the updating steps

**Comment by HAMM3REXTREME** [comment]
Commit 36b6316 should fix this issue
