### ISSUE TITLE
Not an issue but a question as i didn't know how to reach you

### ISSUE THREAD

**Issue by Autantpourmoi** [HAMM3REXTREME/ComfyUI-Installer#5]
just want to know what are the comfy button inside comfyui-installer/images for ? thanks

**Comment by HAMM3REXTREME** [comment]
The icons are there for the desktop entry. There's no official logo for ComfyUI and the placeholder :gear: logo does not look that good in menus, so I made some simple icons. These logos aren't official or anything, you can remove/change them if you want :)

**Comment by Autantpourmoi** [comment]
Thanks , i found out how to use it , that’s why i asked why they were there for , and by chance ( As i’m not so good in computer) , i found out that it start ComfyUI from my app bar , that’s great 
thanks

**Comment by Autantpourmoi** [comment]
just want to know how to add args in launch.sh as i'm trying to --
highvram but it doesn't make any changes , thanks in advannce

**Comment by HAMM3REXTREME** [comment]
Edit the last line in `launch.sh` like so:
` HSA_OVERRIDE_GFX_VERSION=10.3.0 python main.py --highvram $args `
