### ISSUE TITLE
RuntimeError: Found no NVIDIA driver on your system. 

### ISSUE THREAD

**Issue by sclewis90** [HAMM3REXTREME/ComfyUI-Installer#6]
I installed this for AMD and am getting an error https://dpaste.org/utcoX (RuntimeError: Found no NVIDIA driver on your system.)

I cannot run ./ComfyUI. I installed once before and was able to get into the browser app but it would begin processing the prompt then crash. I deleted and reinstalled and now get this error. I am running arch linux with an AMD Radeon 7900xt GPU.

**Comment by HAMM3REXTREME** [comment]
Unless I am missing something, this seems like a bug in ComfyUI, I tried installing it manually and it still errors out.
Try opening an issue in the main ComfyUI repository.

**Comment by sclewis90** [comment]
> Unless I am missing something, this seems like a bug in ComfyUI, I tried installing it manually and it still errors out. Try opening an issue in the main ComfyUI repository.

I will check that out. This is what I get when I install https://dpaste.org/fDMae . 

Seems to be downloading nvidia stuff in the install

**Comment by HAMM3REXTREME** [comment]
I have narrowed it down to some pip dependency being broken.

> Seems to be downloading nvidia stuff in the install
It does download Nvidia stuff even on AMD but that is intentional and needed, maybe some recent update broke something.

**Comment by HAMM3REXTREME** [comment]
ROCm 6.0 with the latest version of ComfyUI fixes this bug. Will be updated in the installer soon.

**Comment by HAMM3REXTREME** [comment]
With the latest ROCm version, ComfyUI does work now.

[amd-log.txt](https://github.com/HAMM3REXTREME/ComfyUI-Installer/files/15181775/amd-log.txt)

**Comment by HAMM3REXTREME** [comment]
ROCm 5.7 PyTorch seems to break ComfyUI. ROCm 6.0 should fix this.
[https://github.com/comfyanonymous/ComfyUI/commit/8cab3be67351a6185945bfecab21ccdfa60d80cd](https://github.com/comfyanonymous/ComfyUI/commit/8cab3be67351a6185945bfecab21ccdfa60d80cd)
I have updated the installer script to install ROCm 6.0, which (hopefully) fixes this issue.
New install script output: https://dpaste.org/h66zA

**Comment by sclewis90** [comment]
Awesome everything installed. Up and running, thank you very much!
